/**
 * Embeds haril_native.node into packages/core/src/ffi/embedded_addon.ts
 * for standalone single-file binary distribution.
 *
 * Usage:
 *   bun run scripts/embed-native.ts          # Embeds available native binaries (x64 and/or arm64)
 *   bun run scripts/embed-native.ts --clean  # Clears embedded payloads
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const embeddedAddonPath = join(root, "packages", "core", "src", "ffi", "embedded_addon.ts");
const pkgPath = join(root, "package.json");

const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
const version: string = pkg.version ?? "0.1.0";

const isClean = process.argv.includes("--clean") || process.argv.includes("--empty");

if (isClean) {
  const content = `/**
 * Embedded binary payload of \`haril_native.node\` for standalone single-file distribution.
 *
 * Generated by \`scripts/embed-native.ts\`. When empty, Haril falls back to
 * loading \`haril_native.node\` from the filesystem or adjacent directories.
 */

export interface EmbeddedPayload {
  version: string;
  base64: string;
}

export const EMBEDDED_NATIVE_PAYLOADS: Partial<Record<"x64" | "arm64", EmbeddedPayload>> = {};
`;
  writeFileSync(embeddedAddonPath, content, "utf8");
  console.log("Cleared embedded native payloads in embedded_addon.ts");
  process.exit(0);
}

const binaries: Array<{ arch: "x64" | "arm64"; path: string }> = [
  { arch: "x64", path: join(root, "native", "out", "bin", "haril_native.node") },
  { arch: "arm64", path: join(root, "native", "out", "bin-arm64", "haril_native.node") },
];

const payloads: Record<string, { version: string; base64: string }> = {};

for (const b of binaries) {
  if (existsSync(b.path)) {
    const buf = readFileSync(b.path);
    const b64 = buf.toString("base64");
    payloads[b.arch] = {
      version,
      base64: b64,
    };
    const kb = (buf.length / 1024).toFixed(1);
    const b64Kb = (b64.length / 1024).toFixed(1);
    console.log(`Embedded ${b.arch} native addon from ${b.path} (${kb} KB -> ${b64Kb} KB base64)`);
  }
}

const embeddedArchs = Object.keys(payloads);
if (embeddedArchs.length === 0) {
  console.warn("WARNING: No native addons found in native/out/bin or native/out/bin-arm64.");
  console.warn("Run 'bun run build:native' before building a standalone executable.");
}

const lines: string[] = [
  `/**`,
  ` * Embedded binary payload of \`haril_native.node\` for standalone single-file distribution.`,
  ` *`,
  ` * Generated by \`scripts/embed-native.ts\`. When empty, Haril falls back to`,
  ` * loading \`haril_native.node\` from the filesystem or adjacent directories.`,
  ` */`,
  ``,
  `export interface EmbeddedPayload {`,
  `  version: string;`,
  `  base64: string;`,
  `}`,
  ``,
  `export const EMBEDDED_NATIVE_PAYLOADS: Partial<Record<"x64" | "arm64", EmbeddedPayload>> = {`,
];

for (const [arch, p] of Object.entries(payloads)) {
  lines.push(`  "${arch}": {`);
  lines.push(`    version: ${JSON.stringify(p.version)},`);
  lines.push(`    base64: "${p.base64}",`);
  lines.push(`  },`);
}

lines.push(`};`);
lines.push(``);

writeFileSync(embeddedAddonPath, lines.join("\n"), "utf8");
console.log(`Updated ${embeddedAddonPath} with [${embeddedArchs.join(", ")}] payloads.`);
